# Site settings
baseurl = "https://blog.bitclvx.com/"
languageCode = "en-us"
title = "Periferia Binaria"
theme = "spectre-pixel"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-166845382-1"

enableRobotsTXT = true
canonifyURLs = true

[params]
  name = "Luis Michael Ibarra"
  altName = "Clvx"
  description = "cat /dev/brain 2&> /dev/null"
  bio = "I build, break, fix, and run stuff professionaly"
  enableRSS = true

  # Author information in posts
  aboutAuthor = "I build, break, fix, and run stuff professionaly"

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = [
    "https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css"
  ]
  customJS  = []

  # The variables below are optionally too and can be used to
  # translate or customize each string of the theme.

  # Navigation links
	home = ""
	subscribe = ""

	# Pagination links
	olderPosts = ""
	newerPosts = ""
	copyright = ""

	# 404 page
	title404 = ""
	subtitle404 = ""

# Add additional social link entries underneath
[social]
	github   = "https://www.github.com/clvx"
	linkedin = "https://www.linkedin.com/in/clvx"
	twitter  = "https://www.twitter.com/clvx"

[taxonomies]
  tag = "tags"
