name: CI

on: [push]

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: clvx/hugo-action@master
    - uses: actions/upload-artifact@v1
      with:
        name: blog
        path: public/
